language: cpp
sudo: required
dist: trusty
compiler: gcc

install:
- sudo apt-get install build-essential
- sudo apt-get install cmake
- sudo apt-get install libgtest.dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo apt-get install lcov
- sudo apt-get install python-pip
- pip install --user cpp-coveralls

env:
- COVERALLS_REPO_TOKEN=8egNx7uP66rbO3ujaoxWwJL7Iient78vm

script:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
- make -j
- make coverage

after_success:
- coveralls -e ARF -e bench -e /usr/include/gtest -e /usr/lib/gcc/x86_64-linux-gnu/5 -e 5