dist: trusty
language: cpp
compiler: gcc
sudo: required

addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- gcc-5
- g++-5

install:
- sudo apt-get install build-essential
- sudo apt-get install cmake
- sudo apt-get install libgtest.dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo apt-get install lcov
- sudo apt-get install python-pip
- pip install --user cpp-coveralls

script:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
- make -j
- make coverage

after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'