language: cpp
matrix:
include:
# linux build on g++4.9
- os: linux
sudo: required
dist: trusty
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- g++-4.9
env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

# linux build on g++5
- os: linux
sudo: required
dist: trusty
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- g++-5
env:
- MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

# linux build on g++6
- os: linux
sudo: required
dist: trusty
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- g++-6
env:
- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo apt-get install build-essential
- sudo apt-get install cmake
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version
- sudo apt-get install libgtest.dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo apt-get install lcov
- sudo apt-get install python-pip
- pip install --user cpp-coveralls

env:
- COVERALLS_REPO_TOKEN=8egNx7uP66rbO3ujaoxWwJL7Iient78vm

script:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
- make -j
- make coverage

after_success:
- coveralls -e ARF -e bench -e /usr/include/gtest -e /usr/lib/gcc/x86_64-linux-gnu/5 -e 5